### ISSUE TITLE
Guild search -classic (wrath)

### ISSUE THREAD

**Issue by Gankenz** [Talryn/GuildSearch#1]
Guild search isn't working in classic. Any chance it could be updated to work for wrath? When clicking show upon a search an error is returned stating "could not find guild frames"
![IMG_20220925_104909](https://user-images.githubusercontent.com/114354513/192155247-566fe523-5cb3-42bc-917c-d9b5e4720022.jpg)

**Comment by Talryn** [comment]
Thanks for reporting it.  Fixed with 9.2.3 I just released.

**Comment by Gankenz** [comment]
Thank you so much sir! This addon is our number one most important addon. We are the largest guild in wow. Over 10,000 guild members. Scrolling is not reasonable. This addon is our savior. Thank you sir! You are amazing!
